project:
  type: website
  output-dir: docs

website:
  title: "Emily L. Norton"
  favicon: favicon1_sm.jpg
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd 
      - research.qmd
      - teaching.qmd
      - posts.qmd

    left:
      - icon: github
        href: https://github.com/mlenorton
        aria-label: GitHub 
      - icon: linkedin
        href: https://www.linkedin.com/in/emily-norton-3b684315/
        aria-label: LinkedIn

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    code-fold: true
    code-summary: "Show the code"

editor: visual

execute:
  freeze: auto  # re-render only when source changes

